[pytest]
markers =
    asyncio: mark test as an asyncio coroutine
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = --strict-markers
asyncio_default_fixture_loop_scope = function
